# -*- coding: utf-8 -*-
"""DL1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1COKRos18T2-ciF-MNHplvbwUqwQZvyg7
"""

import tensorflow as tf
import matplotlib.pyplot as plt

(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.fashion_mnist.load_data()

train_images = train_images / 255.0
test_images = test_images / 255.0

# Visualizing data

print(train_images.shape)
print(test_images.shape)

print(train_labels)

plt.imshow(train_images[1], cmap='gray')
plt.show()

# Defining neural network model

my_model = tf.keras.models.Sequential()
my_model.add(tf.keras.layers.Flatten(input_shape=(28, 28)))
my_model.add(tf.keras.layers.Dense(128, activation='relu'))
my_model.add(tf.keras.layers.Dense(10, activation='softmax'))

my_model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Training the model

my_model.fit(train_images, train_labels, epochs=10)

# Checking model accuracy on test data

val_loss, val_acc = my_model.evaluate(test_images, test_labels)
print("Test accuracy:", val_acc)

# Saving the model

my_model.save("my_fashion_mnist_model.keras")